services:
  - type: web
    name: qu-tip-proxy
    env: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/yourusername/qu-tip-proxy  # Your GitHub repo
    plan: free
    # The application runs on port 8000, which is the default for uvicorn 
    # and is automatically detected by Render.
    # Optional: Set the command explicitly if not using CMD in Dockerfile
    # command: uvicorn quantum_proxy:app --host 0.0.0.0 --port 8000
